trigger: none

pool: praveenagentpool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    backendServiceArm: 'todo_service'
    backendAzureRmStorageAccountName: 'praveenstg'
    backendAzureRmContainerName: 'praveencont'
    backendAzureRmKey: 'p.tfstate'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'todo_service' 
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'

- task: TerraformTask@5
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    environmentServiceNameAzureRM: 'todo_service'
    commandOptions: '-auto-approve'